
import React, { useState } from 'react';
import { User, UserRole, Plan } from '../types';
import { UserPlus, Trash2, Key, Calendar, Shield, Users, Mail, Smartphone, Lock, Package, Clock, Copy, RotateCcw, CheckCircle2, RefreshCw, Edit2, X } from 'lucide-react';

interface UserManagementProps {
  users: User[];
  currentUser: User;
  setUsers: React.Dispatch<React.SetStateAction<User[]>>;
  plans: Plan[];
  apiBase: string;
}

const OTP_BRIDGE_URL = 'https://ifastx.in/wa/waotmail.php';
const AUTH_TOKEN = 'ifastx_internal_bridge_9922';

const UserManagement: React.FC<UserManagementProps> = ({ users, currentUser, setUsers, plans, apiBase }) => {
  const [isAdding, setIsAdding] = useState(false);
  const [editingUser, setEditingUser] = useState<User | null>(null);
  const [copiedUserId, setCopiedUserId] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState<string | null>(null);

  const [formData, setFormData] = useState({ 
    username: '', 
    email: '', 
    mobile: '', 
    password: '', 
    role: UserRole.ADMIN,
    planId: 'p_basic',
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  });

  const [editFormData, setEditFormData] = useState({
    username: '',
    email: '',
    mobile: '',
    password: '',
    role: UserRole.ADMIN,
    planId: '',
    expiryDate: '',
    customMaxInstances: '',
    customDailyLimit: ''
  });

  const handleCopyKey = (userId: string, key: string) => {
    navigator.clipboard.writeText(key);
    setCopiedUserId(userId);
    setTimeout(() => setCopiedUserId(null), 2000);
  };

  const handleRegenerateKey = (userId: string) => {
    const confirmation = window.confirm(
      "SECURITY WARNING: Regenerating the API Key will immediately invalidate the current key. " +
      "Any external applications or integrations using the old key will STOP WORKING. " +
      "Are you sure you want to proceed?"
    );

    if (!confirmation) return;

    const newKey = `sk_live_${Math.random().toString(36).substring(2, 10)}_${Math.random().toString(36).substring(2, 10)}`;
    
    // In a real app, this should call PATCH /api/users/:id
    setUsers(prev => prev.map(u => 
      u.id === userId ? { ...u, apiKey: newKey } : u
    ));

    alert("API Key rotated successfully. Please notify the user to update their integrations.");
  };

  const handleRegeneratePassword = async (user: User) => {
    if (!user.email) {
      alert("Error: This user does not have an email address associated with their account. Password cannot be sent.");
      return;
    }

    const confirmation = window.confirm(
      `Are you sure you want to regenerate the password for ${user.username}? ` +
      `The new password will be sent to ${user.email} immediately.`
    );

    if (!confirmation) return;

    setIsProcessing(user.id);
    const newPassword = Math.random().toString(36).slice(-10);
    
    const emailBody = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 30px; color: #0b141a; background-color: #f0f2f5; border-radius: 15px;">
        <div style="background-color: #ffffff; padding: 40px; border-radius: 20px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); border: 1px solid #e1e4e8;">
          <h2 style="color: #25D366; margin-bottom: 20px; border-bottom: 2px solid #f0f2f5; padding-bottom: 15px;">iFastX Account Security Update</h2>
          <p>Hello <strong>${user.username}</strong>,</p>
          <p>Your account password has been regenerated by the system administrator. Please use the temporary credentials below to access the WA Gateway dashboard.</p>
          
          <div style="background-color: #f8fafc; padding: 25px; text-align: center; border-radius: 12px; border: 1px dashed #cbd5e1; margin: 25px 0;">
            <p style="text-transform: uppercase; font-size: 10px; font-weight: 900; color: #64748b; margin-bottom: 10px; letter-spacing: 1px;">New Access Password</p>
            <span style="font-size: 28px; font-family: monospace; font-weight: bold; color: #0b141a; letter-spacing: 2px;">${newPassword}</span>
          </div>
          
          <p style="font-size: 13px; color: #475569; background-color: #fffbeb; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
            <strong>Security Tip:</strong> We recommend changing your password immediately after logging in.
          </p>
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #f0f2f5; font-size: 11px; color: #94a3b8; text-align: center;">
            <p>&copy; 2024 iFastX Technologies. Secure Enterprise Solutions.</p>
            <p>This is an automated system message, please do not reply.</p>
          </div>
        </div>
      </div>
    `;

    try {
      const response = await fetch(OTP_BRIDGE_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          token: AUTH_TOKEN,
          to: user.email,
          subject: `Security Alert: Your iFastX Gateway Password has been Reset`,
          body: emailBody
        })
      });

      const data = await response.json();
      if (data.success) {
        // Update password at backend
        await fetch(`${apiBase}/api/users/${user.id}/password`, {
          method: 'PATCH',
          headers: { 
            'Content-Type': 'application/json',
            'X-User-ID': currentUser.id,
            'X-Role': currentUser.role,
            'X-API-Key': currentUser.apiKey
          },
          body: JSON.stringify({ password: newPassword })
        });

        setUsers(prev => prev.map(u => u.id === user.id ? { ...u, password: newPassword } : u));
        alert(`Success! A new password has been generated and sent to ${user.email}.`);
      } else {
        alert("Failed to send the new password email. The system update has been rolled back.");
      }
    } catch (err) {
      alert("Network error: Could not reach the email bridge. Password regeneration aborted.");
    } finally {
      setIsProcessing(null);
    }
  };

  const handleAddUser = async () => {
    if (!formData.username || !formData.email || !formData.password) {
      alert("Please fill in Username, Email, and Password.");
      return;
    }
    
    setIsProcessing('creating');
    const newUserObj = {
      id: `u_${Date.now()}`,
      username: formData.username,
      email: formData.email,
      mobile: formData.mobile,
      password: formData.password,
      role: formData.role,
      parentId: currentUser.id,
      apiKey: `sk_live_${Math.random().toString(36).substring(2, 10)}`,
      subscription: {
        planId: formData.planId,
        status: 'active',
        expiryDate: new Date(formData.expiryDate).toISOString(),
      }
    };

    try {
      const res = await fetch(`${apiBase}/api/users`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'X-User-ID': currentUser.id,
          'X-Role': currentUser.role,
          'X-API-Key': currentUser.apiKey
        },
        body: JSON.stringify(newUserObj)
      });

      if (res.ok) {
        const createdUser = await res.json();
        setUsers(prev => [...prev, createdUser]);
        setIsAdding(false);
        setFormData({ 
          username: '', 
          email: '', 
          mobile: '', 
          password: '', 
          role: UserRole.ADMIN, 
          planId: 'p_basic',
          expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
        });
      } else {
        const err = await res.json();
        alert("Backend Error: " + (err.error || 'Failed to create user'));
      }
    } catch (e) {
      alert("Network error connecting to backend API.");
    } finally {
      setIsProcessing(null);
    }
  };

  const handleDeleteUser = async (id: string) => {
    if (confirm("Delete this user? All their instances will be inaccessible.")) {
      try {
        const res = await fetch(`${apiBase}/api/users/${id}`, {
          method: 'DELETE',
          headers: { 
            'X-User-ID': currentUser.id,
            'X-Role': currentUser.role,
            'X-API-Key': currentUser.apiKey
          }
        });
        if (res.ok) {
          setUsers(prev => prev.filter(u => u.id !== id));
        } else {
          const err = await res.json();
          alert("Delete failed: " + err.error);
        }
      } catch (e) {
        alert("Network error");
      }
    }
  };

  const openEditModal = (user: User) => {
    setEditingUser(user);
    setEditFormData({
      username: user.username,
      email: user.email || '',
      mobile: user.mobile || '',
      password: '', // Leave blank unless changing
      role: user.role,
      planId: user.subscription?.planId || '',
      expiryDate: user.subscription?.expiryDate ? new Date(user.subscription.expiryDate).toISOString().split('T')[0] : '',
      customMaxInstances: user.subscription?.customMaxInstances !== undefined && user.subscription?.customMaxInstances !== null ? String(user.subscription.customMaxInstances) : '',
      customDailyLimit: user.subscription?.customDailyLimit !== undefined && user.subscription?.customDailyLimit !== null ? String(user.subscription.customDailyLimit) : ''
    });
  };

  const handleSaveEdit = async () => {
    if (!editingUser) return;
    setIsProcessing('editing');

    const updatePayload: any = {
      username: editFormData.username,
      email: editFormData.email,
      mobile: editFormData.mobile,
      role: editFormData.role,
      planId: editFormData.planId,
      expiryDate: editFormData.expiryDate ? new Date(editFormData.expiryDate).toISOString() : null,
      customMaxInstances: editFormData.customMaxInstances === '' ? null : parseInt(editFormData.customMaxInstances),
      customDailyLimit: editFormData.customDailyLimit === '' ? null : parseInt(editFormData.customDailyLimit)
    };

    if (editFormData.password) {
      updatePayload.password = editFormData.password;
    }

    try {
      const res = await fetch(`${apiBase}/api/users/${editingUser.id}`, {
        method: 'PUT',
        headers: { 
          'Content-Type': 'application/json',
          'X-User-ID': currentUser.id,
          'X-Role': currentUser.role,
          'X-API-Key': currentUser.apiKey
        },
        body: JSON.stringify(updatePayload)
      });

      if (res.ok) {
        setUsers(prev => prev.map(u => {
          if (u.id === editingUser.id) {
            return {
              ...u,
              username: updatePayload.username,
              email: updatePayload.email,
              mobile: updatePayload.mobile,
              role: updatePayload.role,
              subscription: {
                ...u.subscription,
                planId: updatePayload.planId,
                expiryDate: updatePayload.expiryDate,
                status: (updatePayload.expiryDate === null || new Date(updatePayload.expiryDate) > new Date()) ? 'active' : u.subscription?.status,
                customMaxInstances: updatePayload.customMaxInstances,
                customDailyLimit: updatePayload.customDailyLimit
              }
            };
          }
          return u;
        }));
        setEditingUser(null);
      } else {
        const err = await res.json();
        alert("Update failed: " + (err.error || 'Unknown error'));
      }
    } catch (e) {
      alert("Network error connecting to backend API.");
    } finally {
      setIsProcessing(null);
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-3">
            <Users className="text-[#25D366]" />
            {currentUser.role === UserRole.RESELLER ? 'My Sub-Admins' : 'Global User Directory'}
          </h2>
          <p className="text-xs text-gray-500 mt-1 uppercase tracking-widest font-black">
            Total Management: {users.length} Account(s)
          </p>
        </div>
        <button 
          onClick={() => setIsAdding(true)}
          className="bg-[#25D366] hover:bg-[#128c7e] text-[#0b141a] px-4 py-2.5 rounded-xl font-bold flex items-center gap-2 transition-all shadow-lg shadow-green-500/10"
        >
          <UserPlus size={18} />
          Create New User
        </button>
      </div>

      {isAdding && (
        <div className="bg-[#111b21] rounded-2xl border border-[#25D366]/30 p-8 shadow-2xl animate-in fade-in slide-in-from-top-4 duration-300">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Username</label>
              <div className="relative">
                <input 
                  type="text"
                  value={formData.username}
                  onChange={(e) => setFormData(p => ({ ...p, username: e.target.value }))}
                  placeholder="e.g. john_doe"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white focus:ring-2 ring-[#25D366]/50 outline-none"
                />
                <Smartphone className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Email Address</label>
              <div className="relative">
                <input 
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData(p => ({ ...p, email: e.target.value }))}
                  placeholder="john@example.com"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white focus:ring-2 ring-[#25D366]/50 outline-none"
                />
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Mobile Number</label>
              <div className="relative">
                <input 
                  type="text"
                  value={formData.mobile}
                  onChange={(e) => setFormData(p => ({ ...p, mobile: e.target.value }))}
                  placeholder="e.g. 919876543210"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white focus:ring-2 ring-[#25D366]/50 outline-none"
                />
                <Smartphone className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Password</label>
              <div className="relative">
                <input 
                  type="password"
                  value={formData.password}
                  onChange={(e) => setFormData(p => ({ ...p, password: e.target.value }))}
                  placeholder="••••••••"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white focus:ring-2 ring-[#25D366]/20 focus:border-[#25D366] outline-none"
                />
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Assign Role</label>
              <div className="relative">
                <select 
                  value={formData.role}
                  onChange={(e) => setFormData(p => ({ ...p, role: e.target.value as UserRole }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white outline-none appearance-none"
                >
                  {currentUser.role === UserRole.SUPERADMIN && <option value={UserRole.RESELLER}>Reseller</option>}
                  <option value={UserRole.ADMIN}>Admin</option>
                </select>
                <Shield className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Assign Plan</label>
              <div className="relative">
                <select 
                  value={formData.planId}
                  onChange={(e) => setFormData(p => ({ ...p, planId: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white outline-none appearance-none"
                >
                  {plans.map(p => (
                    <option key={p.id} value={p.id}>{p.name} (${p.price})</option>
                  ))}
                </select>
                <Package className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
            <div>
              <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Expiry Date</label>
              <div className="relative">
                <input 
                  type="date"
                  value={formData.expiryDate}
                  onChange={(e) => setFormData(p => ({ ...p, expiryDate: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl pl-10 pr-4 py-3 text-white focus:ring-2 ring-[#25D366]/50 outline-none"
                />
                <Clock className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" size={16} />
              </div>
            </div>
          </div>
          <div className="flex justify-end gap-3 mt-8">
            <button onClick={() => setIsAdding(false)} className="px-6 py-2.5 text-gray-400 hover:text-white font-bold transition-all">Cancel</button>
            <button 
              onClick={handleAddUser} 
              disabled={isProcessing === 'creating'}
              className="bg-[#25D366] text-[#0b141a] px-8 py-2.5 rounded-xl font-black uppercase tracking-widest shadow-lg shadow-green-500/10 transition-all active:scale-95 disabled:opacity-50"
            >
              {isProcessing === 'creating' ? 'Processing...' : 'Provision Account'}
            </button>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {users.filter(u => u.id !== currentUser.id).map(user => {
          const plan = plans.find(p => p.id === user.subscription?.planId);
          return (
            <div key={user.id} className="bg-[#111b21] border border-gray-800 rounded-2xl p-6 hover:border-gray-700 transition-all flex flex-col group shadow-xl relative overflow-hidden">
              {isProcessing === user.id && (
                <div className="absolute inset-0 bg-[#0b141a]/60 backdrop-blur-sm z-20 flex flex-col items-center justify-center space-y-3">
                   <RefreshCw className="animate-spin text-[#25D366]" size={32} />
                   <p className="text-xs font-black uppercase tracking-widest text-[#25D366]">Updating Account Credentials...</p>
                </div>
              )}

              <div className="flex justify-between items-start mb-4">
                  <div className="flex items-center gap-3">
                      <div className={`w-14 h-14 rounded-xl flex items-center justify-center ${
                          user.role === UserRole.RESELLER ? 'bg-purple-500/10 text-purple-400' : 'bg-blue-500/10 text-blue-400'
                      }`}>
                          <Shield size={28} />
                      </div>
                      <div>
                          <h4 className="font-bold text-white group-hover:text-[#25D366] transition-colors text-lg">{user.username}</h4>
                          <div className="flex flex-wrap items-center gap-3 mt-1">
                              <span className="text-[10px] text-gray-500 font-mono flex items-center gap-1">
                                  <Mail size={10} /> {user.email || 'No email'}
                              </span>
                              {user.mobile && (
                                <span className="text-[10px] text-gray-500 font-mono flex items-center gap-1">
                                    <Smartphone size={10} /> {user.mobile}
                                </span>
                              )}
                          </div>
                      </div>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={() => openEditModal(user)} className="p-2 text-gray-600 hover:text-blue-500 transition-colors bg-[#0b141a] rounded-lg border border-gray-800"><Edit2 size={16} /></button>
                    <button onClick={() => handleDeleteUser(user.id)} className="p-2 text-gray-600 hover:text-red-500 transition-colors bg-[#0b141a] rounded-lg border border-gray-800"><Trash2 size={16} /></button>
                  </div>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                  <div className="p-3 bg-black/20 rounded-xl border border-gray-800 space-y-2">
                      <div className="flex items-center justify-between text-[10px] font-black uppercase tracking-tighter">
                          <span className="text-gray-500">Subscription Status</span>
                          <span className={user.subscription && new Date(user.subscription.expiryDate) < new Date() ? "text-red-500" : "text-[#25D366]"}>
                            {user.subscription && new Date(user.subscription.expiryDate) < new Date() ? "EXPIRED" : "ACTIVE"}
                          </span>
                      </div>
                      <div className="flex items-center justify-between">
                          <span className="text-white text-sm font-bold">
                            {plan?.name || 'Basic'}
                            {(user.subscription?.customMaxInstances != null || user.subscription?.customDailyLimit != null) && 
                              <span className="text-[10px] text-blue-400 ml-2 font-normal">(Custom Limits)</span>
                            }
                          </span>
                          <Package size={14} className="text-gray-600" />
                      </div>
                  </div>
                  <div className="p-3 bg-black/20 rounded-xl border border-gray-800 space-y-2">
                      <div className="flex items-center justify-between text-[10px] font-black uppercase tracking-tighter">
                          <span className="text-gray-500">Validity Expiry</span>
                          <Clock size={12} className="text-gray-600" />
                      </div>
                      <div className="text-white text-sm font-bold">
                        {user.subscription ? new Date(user.subscription.expiryDate).toLocaleDateString() : 'Trial'}
                      </div>
                  </div>
              </div>

              <div className="mt-4 pt-4 border-t border-gray-800 space-y-3">
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <Key size={14} className="text-gray-600" />
                      <span className="text-[10px] text-gray-500 font-black uppercase tracking-widest">API Integration Key</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 bg-black/20 p-2 rounded-xl border border-gray-800">
                    <code className="text-[10px] text-gray-400 font-mono truncate flex-1 px-1">
                      {user.apiKey}
                    </code>
                    <div className="flex items-center gap-1 border-l border-gray-800 pl-1">
                      <button 
                        onClick={() => handleCopyKey(user.id, user.apiKey)}
                        className="p-1.5 text-gray-500 hover:text-[#25D366] transition-all active:scale-90"
                        title="Copy API Key"
                      >
                        {copiedUserId === user.id ? <CheckCircle2 size={14} className="text-[#25D366]" /> : <Copy size={14} />}
                      </button>
                      <button 
                        onClick={() => handleRegenerateKey(user.id)}
                        className="p-1.5 text-gray-500 hover:text-yellow-500 transition-all active:scale-90"
                        title="Rotate / Regenerate API Key"
                      >
                        <RotateCcw size={14} />
                      </button>
                    </div>
                  </div>
                </div>

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <Lock size={14} className="text-gray-600" />
                      <span className="text-[10px] text-gray-500 font-black uppercase tracking-widest">Account Credentials</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 bg-black/20 p-2 rounded-xl border border-gray-800">
                    <div className="flex-1 px-1 flex items-center gap-2">
                        <span className="text-[10px] text-gray-400 font-mono">PWD: ••••••••</span>
                        <span className="text-[9px] text-gray-600 italic">(Secured)</span>
                    </div>
                    <div className="flex items-center gap-1 border-l border-gray-800 pl-1">
                      <button 
                        onClick={() => handleRegeneratePassword(user)}
                        className="p-1.5 text-gray-500 hover:text-orange-500 transition-all active:scale-90 flex items-center gap-1.5"
                        title="Reset & Send Password to Email"
                      >
                        <RefreshCw size={14} />
                        <span className="text-[9px] font-black uppercase">Reset PWD</span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {editingUser && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-[#111b21] rounded-2xl border border-gray-800 p-6 w-full max-w-3xl shadow-2xl overflow-y-auto max-h-[90vh]">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-white flex items-center gap-2">
                <Edit2 className="text-blue-500" />
                Edit User: {editingUser.username}
              </h3>
              <button onClick={() => setEditingUser(null)} className="text-gray-500 hover:text-white">
                <X size={24} />
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Username</label>
                <input 
                  type="text"
                  value={editFormData.username}
                  onChange={(e) => setEditFormData(p => ({ ...p, username: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Email</label>
                <input 
                  type="email"
                  value={editFormData.email}
                  onChange={(e) => setEditFormData(p => ({ ...p, email: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Mobile</label>
                <input 
                  type="text"
                  value={editFormData.mobile}
                  onChange={(e) => setEditFormData(p => ({ ...p, mobile: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">New Password (Optional)</label>
                <input 
                  type="password"
                  value={editFormData.password}
                  onChange={(e) => setEditFormData(p => ({ ...p, password: e.target.value }))}
                  placeholder="Leave blank to keep current"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Role</label>
                <select 
                  value={editFormData.role}
                  onChange={(e) => setEditFormData(p => ({ ...p, role: e.target.value as UserRole }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white outline-none"
                >
                  {currentUser.role === UserRole.SUPERADMIN && <option value={UserRole.RESELLER}>Reseller</option>}
                  <option value={UserRole.ADMIN}>Admin</option>
                </select>
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Plan</label>
                <select 
                  value={editFormData.planId}
                  onChange={(e) => setEditFormData(p => ({ ...p, planId: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white outline-none"
                >
                  {plans.map(p => (
                    <option key={p.id} value={p.id}>{p.name} (${p.price})</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Expiry Date</label>
                <input 
                  type="date"
                  value={editFormData.expiryDate}
                  onChange={(e) => setEditFormData(p => ({ ...p, expiryDate: e.target.value }))}
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Custom Instance Limit (Optional)</label>
                <input 
                  type="number"
                  value={editFormData.customMaxInstances}
                  onChange={(e) => setEditFormData(p => ({ ...p, customMaxInstances: e.target.value }))}
                  placeholder="Overrides plan limit"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-500 uppercase tracking-widest mb-2">Custom Daily Msg Limit (Optional)</label>
                <input 
                  type="number"
                  value={editFormData.customDailyLimit}
                  onChange={(e) => setEditFormData(p => ({ ...p, customDailyLimit: e.target.value }))}
                  placeholder="Overrides plan limit"
                  className="w-full bg-[#202c33] border border-gray-700 rounded-xl px-4 py-3 text-white focus:ring-2 ring-blue-500/50 outline-none"
                />
              </div>
            </div>

            <div className="flex justify-end gap-3 mt-8 pt-6 border-t border-gray-800">
              <button onClick={() => setEditingUser(null)} className="px-6 py-2.5 text-gray-400 hover:text-white font-bold transition-all">Cancel</button>
              <button 
                onClick={handleSaveEdit} 
                disabled={isProcessing === 'editing'}
                className="bg-blue-500 hover:bg-blue-600 text-white px-8 py-2.5 rounded-xl font-black uppercase tracking-widest shadow-lg shadow-blue-500/20 transition-all active:scale-95 disabled:opacity-50"
              >
                {isProcessing === 'editing' ? 'Saving...' : 'Save Changes'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default UserManagement;
